/** Seed catalog including Damal Hotel Hargeisa and Holiday Hotel Mogadishu */

export const seedStays = [
  {
    id: 'damal-hotel-hargeisa',
    name: 'Damal Hotel Hargeisa',
    city: 'Hargeisa',
    country: 'Somaliland',
    neighborhood: 'Road 1 · Dahabshiil Business Centre',
    type: 'hotel',
    typeLabel: 'Business Hotel',
    image: '/hotels/damal/cover.jpg',
    gallery: [
      '/hotels/damal/cover.jpg',
      '/hotels/damal/exterior.jpg',
      '/hotels/damal/lobby.jpg',
      '/hotels/damal/deluxe.jpg',
      '/hotels/damal/super.jpg',
      '/hotels/damal/vip.jpg',
      '/hotels/damal/family.jpg',
      '/hotels/damal/resto.jpg',
    ],
    nightlyFrom: 85,
    rating: 4.7,
    reviews: 214,
    guestScore: 9.0,
    badge: 'Bestseller',
    amenities: ['Breakfast Included', 'Wi-Fi', 'Parking', 'Free Cancellation'],
    highlights: ['24h Front Desk', 'Restaurant', 'Airport Shuttle', 'AC', 'Wi-Fi'],
    summary:
      'Modern 4-star hospitality in the heart of Hargeisa near government offices and shopping. About 94–105 rooms across Deluxe, Super Deluxe, Family, and VIP categories with complimentary breakfast, free Wi‑Fi, A/C, and a 24-hour front desk. Ideal for business and transit stays with optional airport transfers.',
    room: {
      name: 'Deluxe Room',
      tag: 'City Centre',
      bed: 'Double Bed',
      guests: 2,
      sizeSqm: 28,
      image: '/hotels/damal/deluxe.jpg',
      blurb:
        'Contemporary furnishings, private bathroom, satellite TV, high-speed Wi‑Fi, and daily breakfast included.',
    },
    map: { lat: 9.5616, lng: 44.064 },
    contact: {
      phone: '+252 65 339 9000',
      website: 'https://damalhotel.com',
      checkIn: '12:00',
      checkOut: '12:00',
    },
    featured: true,
  },
  {
    id: 'holiday-hotel-mogadishu',
    name: 'Holiday Hotel Mogadishu',
    city: 'Mogadishu',
    country: 'Somalia',
    neighborhood: 'KM4 · near Sahal terminal',
    type: 'hotel',
    typeLabel: 'City Hotel',
    image: '/hotels/holiday/hero.jpg',
    gallery: [
      '/hotels/holiday/hero.jpg',
      '/hotels/holiday/exterior.jpg',
      '/hotels/holiday/lobby.jpg',
      '/hotels/holiday/room1.jpg',
      '/hotels/holiday/room2.jpg',
      '/hotels/holiday/room3.jpg',
      '/hotels/holiday/detail.jpg',
    ],
    nightlyFrom: 95,
    rating: 4.6,
    reviews: 128,
    guestScore: 8.9,
    badge: 'New',
    amenities: ['Wi-Fi', 'Parking', 'Breakfast Included', 'Free Cancellation'],
    highlights: ['Secure Compound', 'Restaurant', '24h Desk', 'AC', 'Transfers'],
    summary:
      'Welcoming city hotel in Mogadishu’s KM4 corridor offering secure, comfortable rooms for business and leisure travelers. Expect Somali hospitality, on-site dining, reliable Wi‑Fi, air-conditioned rooms, and concierge help with airport transfers and local arrangements.',
    room: {
      name: 'Standard Twin',
      tag: 'City',
      bed: 'Twin / King',
      guests: 2,
      sizeSqm: 30,
      image: '/hotels/holiday/room1.jpg',
      blurb:
        'Clean air-conditioned room with private bath, workspace, and complimentary breakfast options.',
    },
    map: { lat: 2.0469, lng: 45.3182 },
    contact: {
      phone: '+252 61 3885999',
      email: 'info@holidayhotel.so',
      website: 'https://holidayhotel.so',
      checkIn: '14:00',
      checkOut: '12:00',
    },
    featured: true,
  },
  {
    id: 'address-downtown',
    name: 'Address Downtown Dubai',
    city: 'Dubai',
    country: 'UAE',
    neighborhood: 'Downtown Dubai',
    type: 'hotel',
    typeLabel: 'Luxury Hotel',
    image:
      'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=1400&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1582719508461-905c673771fd?auto=format&fit=crop&w=1400&q=80',
      'https://images.unsplash.com/photo-1618773928121-c32242e63f39?auto=format&fit=crop&w=1200&q=80',
    ],
    nightlyFrom: 320,
    rating: 5.0,
    reviews: 1284,
    guestScore: 9.6,
    badge: 'Bestseller',
    amenities: ['Free Cancellation', 'Breakfast Included', 'Pool', 'Wi-Fi'],
    highlights: ['Burj Views', 'Infinity Pool', 'Breakfast', 'Wi-Fi', 'Parking'],
    summary:
      'Iconic Downtown address with Burj Khalifa views, refined suites, and seamless concierge for business or leisure.',
    room: {
      name: 'Premier City View Room',
      tag: 'City View',
      bed: 'King Bed',
      guests: 2,
      sizeSqm: 65,
      image:
        'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&w=800&q=80',
      blurb: 'Floor-to-ceiling glass, marble bath, and a dedicated work desk.',
    },
    map: { lat: 25.1972, lng: 55.2744 },
    featured: true,
  },
  {
    id: 'four-seasons-dubai',
    name: 'Four Seasons Resort Dubai',
    city: 'Dubai',
    country: 'UAE',
    neighborhood: 'Jumeirah Beach',
    type: 'hotel',
    typeLabel: 'Luxury Resort',
    image:
      'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=1400&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?auto=format&fit=crop&w=1400&q=80',
    ],
    nightlyFrom: 1250,
    rating: 4.9,
    reviews: 482,
    guestScore: 9.6,
    badge: 'Bestseller',
    amenities: ['Private Beach', 'Pool', 'Spa', 'Breakfast Included', 'Wi-Fi'],
    highlights: ['Private Beach', 'Infinity Pool', 'Spa', 'Wi-Fi'],
    summary:
      'Beachfront sanctuary on Jumeirah with infinity pools, spa rituals, and ocean-view suites.',
    room: {
      name: 'Premier Ocean View Room',
      tag: 'Ocean View',
      bed: 'King Bed',
      guests: 2,
      sizeSqm: 65,
      image:
        'https://images.unsplash.com/photo-1611892440504-42a792e24d32?auto=format&fit=crop&w=800&q=80',
      blurb: 'Soft coastal light, private balcony, and resort Wi‑Fi.',
    },
    map: { lat: 25.1412, lng: 55.1853 },
    featured: true,
  },
  {
    id: 'jazeer-hargeisa',
    name: 'Jazeer Hotel',
    city: 'Hargeisa',
    country: 'Somaliland',
    neighborhood: 'City Centre',
    type: 'hotel',
    typeLabel: 'Business Hotel',
    image:
      'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1400&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=1400&q=80',
    ],
    nightlyFrom: 145,
    rating: 4.8,
    reviews: 96,
    guestScore: 9.1,
    amenities: ['Free Cancellation', 'Wi-Fi', 'Parking', 'Breakfast Included'],
    highlights: ['Central', 'Business desk', 'Wi-Fi', 'Parking'],
    summary: 'Reliable city-centre stay with strong connectivity and warm local hospitality.',
    room: {
      name: 'Executive Room',
      tag: 'City',
      bed: 'King Bed',
      guests: 2,
      sizeSqm: 38,
      image:
        'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&w=800&q=80',
      blurb: 'Quiet AC room with desk and verified fiber for calls.',
    },
    map: { lat: 9.56, lng: 44.065 },
    featured: false,
  },
  {
    id: 'maldives-villa',
    name: 'Maldives Overwater Villa',
    city: 'Malé',
    country: 'Maldives',
    neighborhood: 'North Malé Atoll',
    type: 'holiday_home',
    typeLabel: 'Private Villa',
    image:
      'https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=1400&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1439066615861-d1af74d74000?auto=format&fit=crop&w=1400&q=80',
    ],
    nightlyFrom: 1250,
    rating: 4.9,
    reviews: 210,
    guestScore: 9.8,
    badge: 'New',
    amenities: ['Private Beach', 'Pool', 'Kitchen', 'Wi-Fi'],
    highlights: ['Overwater', 'Butler', 'Breakfast', 'Wi-Fi'],
    summary: 'Glass-floor villa with direct lagoon access and a personal butler.',
    room: {
      name: 'Overwater Suite',
      tag: 'Lagoon',
      bed: 'King Bed',
      guests: 2,
      sizeSqm: 120,
      image:
        'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?auto=format&fit=crop&w=800&q=80',
      blurb: 'Open-air bath, plunge deck, and fiber uplink.',
    },
    map: { lat: 4.1755, lng: 73.5093 },
    featured: true,
  },
]

export const LOYALTY = {
  welcomeBonus: 100,
  referralReferrer: 500,
  referralReferee: 250,
  pointsPerDollar: 10,
}
