export const PERMISSIONS = [
  'property:read',
  'property:write',
  'staff:manage',
  'room:manage',
  'rate:manage',
  'inventory:manage',
  'reservation:read',
  'reservation:write',
  'frontdesk:operate',
  'housekeeping:operate',
  'maintenance:operate',
  'finance:read',
  'finance:write',
  'content:manage',
  'analytics:read',
  'onboarding:write',
  'platform:settings',
  'hotel:approve',
  'hotel:suspend',
  'user:impersonate',
  'booking:override',
  'finance:platform',
  'content:moderate',
  'promo:manage',
  'support:manage',
  'audit:read',
  'analytics:platform',
] as const;

export type PermissionCode = (typeof PERMISSIONS)[number];

export const HOTEL_ROLE_PERMISSIONS: Record<string, PermissionCode[]> = {
  HOTEL_OWNER: [
    'property:read',
    'property:write',
    'staff:manage',
    'room:manage',
    'rate:manage',
    'inventory:manage',
    'reservation:read',
    'reservation:write',
    'frontdesk:operate',
    'housekeeping:operate',
    'maintenance:operate',
    'finance:read',
    'finance:write',
    'content:manage',
    'analytics:read',
    'onboarding:write',
  ],
  GROUP_ADMIN: [
    'property:read',
    'property:write',
    'staff:manage',
    'room:manage',
    'rate:manage',
    'inventory:manage',
    'reservation:read',
    'reservation:write',
    'frontdesk:operate',
    'housekeeping:operate',
    'maintenance:operate',
    'finance:read',
    'finance:write',
    'content:manage',
    'analytics:read',
    'onboarding:write',
  ],
  GENERAL_MANAGER: [
    'property:read',
    'property:write',
    'staff:manage',
    'room:manage',
    'rate:manage',
    'inventory:manage',
    'reservation:read',
    'reservation:write',
    'frontdesk:operate',
    'housekeeping:operate',
    'maintenance:operate',
    'finance:read',
    'content:manage',
    'analytics:read',
  ],
  RESERVATION_MANAGER: [
    'property:read',
    'room:manage',
    'inventory:manage',
    'reservation:read',
    'reservation:write',
    'analytics:read',
  ],
  FRONT_DESK: [
    'property:read',
    'reservation:read',
    'reservation:write',
    'frontdesk:operate',
  ],
  REVENUE_MANAGER: [
    'property:read',
    'rate:manage',
    'inventory:manage',
    'reservation:read',
    'analytics:read',
  ],
  ACCOUNTANT: [
    'property:read',
    'reservation:read',
    'finance:read',
    'finance:write',
    'analytics:read',
  ],
  HOUSEKEEPING_MANAGER: ['property:read', 'housekeeping:operate'],
  HOUSEKEEPING_STAFF: ['property:read', 'housekeeping:operate'],
  MAINTENANCE_STAFF: ['property:read', 'maintenance:operate'],
  CONTENT_MANAGER: ['property:read', 'property:write', 'content:manage'],
  READ_ONLY_ANALYST: [
    'property:read',
    'reservation:read',
    'finance:read',
    'analytics:read',
  ],
};

export const PLATFORM_ROLE_PERMISSIONS: Record<string, PermissionCode[]> = {
  SUPER_ADMIN: [
    'platform:settings',
    'hotel:approve',
    'hotel:suspend',
    'user:impersonate',
    'booking:override',
    'finance:platform',
    'content:moderate',
    'promo:manage',
    'support:manage',
    'audit:read',
    'analytics:platform',
    'property:read',
    'property:write',
    'staff:manage',
  ],
  OPERATIONS_ADMIN: [
    'hotel:approve',
    'hotel:suspend',
    'booking:override',
    'support:manage',
    'audit:read',
    'analytics:platform',
    'property:read',
  ],
  FINANCE_ADMIN: [
    'finance:platform',
    'audit:read',
    'analytics:platform',
    'property:read',
  ],
  CUSTOMER_SUPPORT: [
    'support:manage',
    'booking:override',
    'user:impersonate',
    'audit:read',
    'property:read',
    'reservation:read',
  ],
  HOTEL_ONBOARDING_OFFICER: [
    'hotel:approve',
    'property:read',
    'onboarding:write',
    'audit:read',
  ],
  CONTENT_MODERATOR: ['content:moderate', 'property:read', 'audit:read'],
  MARKETING_MANAGER: ['promo:manage', 'analytics:platform', 'property:read'],
  DATA_ANALYST: ['analytics:platform', 'property:read', 'audit:read'],
  READ_ONLY_AUDITOR: ['audit:read', 'analytics:platform', 'property:read'],
};
